/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pixel_polaroid_camera/scene.gltf -o Camera.jsx 
Author: soupffle (https://sketchfab.com/soupffle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pixel-polaroid-camera-4b92c2d96bf944a2b94a4cc27dea32b6
Title: Pixel Polaroid Camera
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="M90CameraLens_A_1" position={[0, 0, -0.15]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.InstaxMini90} />
              </group>
              <group name="M90CameraLens_B_2" position={[0, 0, -0.1]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.InstaxMini90} />
              </group>
              <group name="M90CameraLens_C_3" position={[0, 0, -0.05]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.InstaxMini90} />
              </group>
              <group name="M90CameraBase_0">
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.InstaxMini90} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
