/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/intaxmini12.glb -o src/components/Instax12.jsx -r public 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/intaxmini12.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="NurbsPath" position={[0.397, 0, -1.01]} rotation={[0, 0, -Math.PI / 2]} />
        <group name="Plane001" visible={false} position={[0.397, 2.258, -1.01]}>
          <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.004']} />
          <mesh name="Plane005_1" geometry={nodes.Plane005_1.geometry} material={materials['Material.005']} />
        </group>
        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.metal} position={[-1.685, -0.861, 0.18]} rotation={[0, 0.518, 0]} scale={[0.558, 0.504, 0.558]} />
        <mesh name="Object_7001" geometry={nodes.Object_7001.geometry} material={materials.metal} position={[-1.685, -0.861, -0.407]} rotation={[0, 0.433, 0]} scale={[-0.558, -0.504, -0.558]} />
        <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Ikae} position={[-1.685, -0.861, 0.18]} rotation={[0, 0.518, 0]} scale={[0.558, 0.504, 0.558]} />
        <mesh name="Object_8001" geometry={nodes.Object_8001.geometry} material={materials.Ikae} position={[-1.685, -0.861, -0.407]} rotation={[0, 0.433, 0]} scale={[-0.558, -0.504, -0.558]} />
        <group name="MAIN_BODY">
          <mesh name="mesh005" geometry={nodes.mesh005.geometry} material={materials['pastel blue']} />
          <mesh name="mesh005_1" geometry={nodes.mesh005_1.geometry} material={materials['Material.001']} />
          <mesh name="mesh005_2" geometry={nodes.mesh005_2.geometry} material={materials['Material.003']} />
          <mesh name="mesh005_3" geometry={nodes.mesh005_3.geometry} material={materials.screws} />
        </group>
        <mesh name="button_2" geometry={nodes.button_2.geometry} material={materials['pastel blue']} position={[-1.524, 0.341, 0.944]} />
        <mesh name="flash" geometry={nodes.flash.geometry} material={materials['Material.006']} position={[-0.649, 1.55, 0.693]} />
        <mesh name="lense" geometry={nodes.lense.geometry} material={materials['pastel blue']} position={[0.502, -0.475, 1.319]} />
        <mesh name="lesne1" geometry={nodes.lesne1.geometry} material={materials['pastel blue']} position={[0.502, -0.475, 1.319]} />
        <group name="lense2" position={[0.502, -0.475, 1.319]}>
          <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['pastel blue']} />
          <mesh name="Cylinder003_1" geometry={nodes.Cylinder003_1.geometry} material={materials['Material.001']} />
          <mesh name="Cylinder003_2" geometry={nodes.Cylinder003_2.geometry} material={materials['Material.002']} />
          <mesh name="lense2001" geometry={nodes.lense2001.geometry} material={materials['Material.001']} position={[0, 0, 0.094]} />
          <mesh name="lense2002" geometry={nodes.lense2002.geometry} material={materials['Material.001']} position={[0, 0, 0.094]} />
          <mesh name="lense2003" geometry={nodes.lense2003.geometry} material={materials.Glass} position={[0, 0, -0.22]} />
        </group>
        <group name="Retopo_MAIN_BODY001">
          <mesh name="mesh011" geometry={nodes.mesh011.geometry} material={materials['pastel blue']} />
          <mesh name="mesh011_1" geometry={nodes.mesh011_1.geometry} material={materials['Material.003']} />
        </group>
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['pastel blue']} position={[0.639, 1.899, -0.639]} />
        <mesh name="BATTERY_COVER" geometry={nodes.BATTERY_COVER.geometry} material={materials['pastel blue']} position={[-1.989, -1.081, -0.151]} />
        <mesh name="BATTERY_COVER001" geometry={nodes.BATTERY_COVER001.geometry} material={materials['Material.001']} position={[-2.003, -1.081, -0.151]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['pastel blue']} position={[0.387, 2.397, 0]} />
        <group name="lense001" position={[0.502, -0.475, 1.319]}>
          <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['pastel blue']} />
          <mesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials.Material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/intaxmini12.glb')
